### ISSUE TITLE
removal of  "laminas/laminas-log"

### ISSUE THREAD

**Issue by arhimede** [dotkernel/dot-form#9]
1. why "laminas/laminas-log"  is included ?  Please investigate. @MarioRadu  said is not the job of the form to log stuff 
2. eventually replace "laminas/laminas-log" with dotkernel-log .  in order to have a single point of failure ....

**Comment by marioradu05** [comment]
A draft PR was created by @Jurj-Bogdan which decouples the package from laminas/laminas-log, but digging more into the issue we found another issue : 

The reason why the #11 PR is a draft is that at this point in time it's useless, because we couldn't test it properly.

The codebase (frontend, maybe admin also) uses it's/their own implementation of some package functionality resulting in some dot-form package methods not being used.

We will need time to investigate why this is happening in the codebase and refactor the functionality to use the dot-form implementation.

**Comment by marioradu05** [comment]
This issue was fixed in https://github.com/dotkernel/dot-form/pull/15.
